---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - First author
  - Another author
thanks: "Code and data are available at: LINK."
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```


# Introduction

You can and should cross-reference sections and sub-sections. For instance, @sec-data and @sec-first-point. 



# Data {#sec-data}

For this experiment we collected our own data exploring whether it is possible to taste the difference between tea first or milk first. Along the way we had some challenges, we had trouble getting exact measurements as the scale could only measure within .5 of a gram. There was also the issue of the cups not being stirred. Lastly, the tester both doesn't normally drink tea but also has a diet without subtle flavours. 


# Model

$$
Pr(\theta | y) = \frac{Pr(y | \theta) Pr(\theta)}{Pr(y)}
$$ {#eq-bayes}

@eq-bayes seems useful, eh?

Here's a dumb example of how to use some references: In paper we run our analysis in `R` [@citeR]. We also use the `tidyverse` which was written by @thereferencecanbewhatever If we were interested in baseball data then @citeLahman could be useful. 

We can use maths by including latex between dollar signs, for instance $\theta$.


# Results

# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

In next steps, we would use a simpler method for adding the milk, such as a measuring scoop, as this would keep the amounts similar without having to use a scale. We would also like to compare the tasting ability across different testers with different tea experience levels and diets. We would also like to control for other factors such as temperature, and steeping level, as some samples were warmer than others affecting the taste. As well, a larger amount of tea allowing for better testing.

\newpage

\appendix

# Appendix {-}


# Additional details


\newpage


# References


